name: GitHub Actions Demo
on: [push]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  Explore-GitHub-Actions:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: 'true'
        token_format: 'access_token' # <--
        workload_identity_provider: 'projects/871186497969/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@august-period-348221.iam.gserviceaccount.com'
        access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list

